esp.deviceList[0].name=s-31-sandbox
esp.deviceList[0].description=Basement lampshade
esp.deviceList[0].location=North east corner
esp.deviceList[0].device-type=PLUG
esp.deviceList[0].telemetry=true
esp.deviceList[0].iotDevice-make=Sonoff
esp.deviceList[0].iotDevice-model=S-31
esp.deviceList[0].enableDataSaver=false
esp.deviceList[0].config.latitude-degrees=43.651070
esp.deviceList[0].config.longitude-degrees=-79.347015
esp.deviceList[0].config.timezone-offset=99
esp.deviceList[0].config.time-dst=0,2,3,1,2,-240
esp.deviceList[0].config.time-std=0,1,11,1,2,-300
esp.deviceList[0].group=HOME
esp.deviceList[0].bridge=TASMOTA

esp.deviceList[1].name=Master Bedroom-Lampshade
esp.deviceList[1].description=Master Bedroom Lampshade
esp.deviceList[1].location=Lampshade on the center table
esp.deviceList[1].device-type=PLUG
esp.deviceList[1].telemetry=false
esp.deviceList[1].iotDevice-make=Ikea
esp.deviceList[1].iotDevice-model=Tretakt
esp.deviceList[1].enableDataSaver=false
esp.deviceList[1].config.latitude-degrees=43.651070
esp.deviceList[1].config.longitude-degrees=-79.347015
esp.deviceList[1].config.timezone-offset=99
esp.deviceList[1].config.time-dst=0,2,3,1,2,-250
esp.deviceList[1].config.time-std=0,1,11,1,2,-300
esp.deviceList[1].group=HOME
esp.deviceList[1].bridge=ZIGBEE2MQTT
