spring.output.ansi.enabled=always
server.port=${PORT}

server.ssl.key-store=classpath:localhost-certificate.p12
#server.ssl.key-store-password=${ENC_SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=springboot

# keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI}
keycloak.username-attribute=preferred_username


#application.security.jwt.token.jwtExpirynMinutes=600
application.security.jwt.token.jwtExpirynMinutes=5

mqtt.hostname=${MQTT_HOSTNAME}
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}

spring.config.import=devices-prod.properties

# commands exposed in the dropdown on Commands page. should be defined in CommandEnum
client-exposed.mqtt.commands=power,teleperiod,latitude,longitude,timezone,timedst,timestd,time
# period in seconds to wait for command to finish execution
command.execution.timeout=5

# telePeriod values are in seconds (0 disables telemetry, max is 3600)
# 46800 = 13 hours
telemetry.period.increase-to=0
telemetry.period.default=600
telemetry.scheduler.increase-task.cron-expression=0 0 17 * * *
telemetry.scheduler.restore-task.cron-expression=0 0 6 * * *

websocket.endpoint=/protected/hangar-iot-websocket
websocket.topics.prefix=/topic


# Actuator
management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoint.beans.access=unrestricted
management.endpoints.web.exposure.include=health,shutdown,beans
application.security.actuator.username=${ACTUATOR_USERNAME}
application.security.actuator.password=${ACTUATOR_PASSWORD}

# allow cors from everywhere in development should override in prod profile
application.security.corsFilter.corsUrlsToAllow=${CORS_URLS_TO_ALLOW}
#application.security.corsFilter.corsMaxAgeInSecs=3600

# Maven placeholders are surrounded by @
build.timestamp=@timestamp@ UTC
build.version=@version@

spring.jackson.mapper.accept-case-insensitive-properties=true

