esp.deviceList[0].name=family-room-light
esp.deviceList[0].description=Family room
esp.deviceList[0].location=South east corner
esp.deviceList[0].device-type=PLUG
esp.deviceList[0].telemetry=false
esp.deviceList[0].iotDevice-make=Sonoff
esp.deviceList[0].iotDevice-model=BasicR2
esp.deviceList[0].enableDataSaver=false
esp.deviceList[0].config.latitude-degrees=43.651070
esp.deviceList[0].config.longitude-degrees=-79.347015
esp.deviceList[0].config.timezone-offset=99
esp.deviceList[0].config.time-dst=0,2,3,1,2,-240
esp.deviceList[0].config.time-std=0,1,11,1,2,-300
esp.deviceList[0].group=HOME

esp.deviceList[1].name=living-room-light
esp.deviceList[1].description=Living room
esp.deviceList[1].location=North corner
esp.deviceList[1].device-type=PLUG
esp.deviceList[1].telemetry=false
esp.deviceList[1].iotDevice-make=Sonoff
esp.deviceList[1].iotDevice-model=BasicR2
esp.deviceList[1].enableDataSaver=false
esp.deviceList[1].config.latitude-degrees=43.651070
esp.deviceList[1].config.longitude-degrees=-79.347015
esp.deviceList[1].config.timezone-offset=99
esp.deviceList[1].config.time-dst=0,2,3,1,2,-240
esp.deviceList[1].config.time-std=0,1,11,1,2,-300
esp.deviceList[1].group=HOME

esp.deviceList[2].name=s-31-sandbox
esp.deviceList[2].description=Office
esp.deviceList[2].location=North east corner
esp.deviceList[2].device-type=PLUG
esp.deviceList[2].telemetry=true
esp.deviceList[2].iotDevice-make=Sonoff
esp.deviceList[2].iotDevice-model=S-31
esp.deviceList[2].enableDataSaver=false
esp.deviceList[2].config.latitude-degrees=43.651070
esp.deviceList[2].config.longitude-degrees=-79.347015
esp.deviceList[2].config.timezone-offset=99
esp.deviceList[2].config.time-dst=0,2,3,1,2,-240
esp.deviceList[2].config.time-std=0,1,11,1,2,-300
esp.deviceList[2].group=HOME

